version: '3.8'
services:
  ethereum-node:
    image: ethereum/client-go:stable
    container_name: ethereum-node
    ports:
      - "8545:8545"
    command:
      --http --http.addr 0.0.0.0 --http.api eth,net,web3
